# Generated by Django 4.1.4 on 2022-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('specialization', models.CharField(max_length=200, verbose_name='Profesion')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='chefs', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de Edicion')),
            ],
            options={
                'verbose_name': 'chef',
                'verbose_name_plural': 'chefs',
                'ordering': ['-created'],
            },
        ),
    ]
